* git
** 找出修改的c文件和头文件
git status |grep modified |grep -E '.c$|.h$'|awk '{print $3}' |xargs
** git机器间克隆
git clone root@10.50.123.52:/home/hello 
** diff
svn status|grep "\.c$"|awk '{print $2}'|xargs svn diff

* grub
** grub 恢复
    grub> root (hd0,0)
    grub> find /boot/grub/stage1
    grub> setup (hd0)
    grub> setup (hd0,0)
* iptables
** nat
iptables -t nat -A POSTROUTING -p tcp -s 192.2.1.0/24 -j SNAT --to-source 10.60.0.235:1024-65535
iptables -t nat -A PREROUTING -p tcp -s 10.60.0.182/255.255.255.255 --dport 443 -j REDIRECT --to-ports 5000

* diff
diff -ENwbur build/ wlc1/ 
** 更新
diff -Naur old_file new_file > patch.1.0
patch -p0 < patch.1.0
#old_file will update 

* find
find . -type f -exec touch {} \; 
* portal
** portal新方法
1.目的地服务器放行， iptables -t nat -I PREROUTING -d 10.50.123.222 -j ACCEPT
2.用户地址段重定向至9000，iptables -t nat -A PREROUTING -p tcp -s 172.168.0.0/255.255.0.0 --dport 80 -j REDIRECT --to-ports 9000
3.认证完用户ip放行（利用ip set提高效率），规则插入在 2 之前 

* eloop
eloop_run有段小技巧：利用select完成timeout

* vi
** 查找
you might first place the cursor on the word "foo" then press * to search for that word. 
** 替换
:%s/vivian/sky/g vi替换所有
:%s/AD_DBG_LVL_\u\+, //g 去掉AD_DBG_LVL_DEBUG,AD_DBG_LVL_INFO之类
:%s/AUDIT_DATA_LOG/LOG_AL/g
:s/\t//g 去掉tab
:%s/foo/bar/gc //Change each 'foo' to 'bar', but ask for confirmation first. 
:%s/\<foo\>/bar/gc //Change only whole words exactly matching 'foo' to 'bar'; ask for confirmation. 
:%s/foo/bar/gci Change each 'foo' (case insensitive due to the i flag) to 'bar'; ask for confirmation. 
:%s/foo/bar/gcI Change each 'foo' (case sensitive due to the I flag) to 'bar'; ask for confirmation. 
:'<,'>s/foo/bar/g 	
When compiled with +visual, change each 'foo' to 'bar' for all lines within a visual selection. Vim automatically appends the visual selection range ('<,'>) for any ex command when you select an area and enter :. Also, see Note below. 
:.,+2s/foo/bar/g 	Change each 'foo' to 'bar' for the current line (.) and the two next lines (+2).
:g/^baz/s/foo/bar/g 	
    Change each 'foo' to 'bar' in each line starting with 'baz'. 
\{#\} is used for repetition. /foo.\{2\} will match foo and the two following characters. The \ is not required on the closing } so /foo.\{2} will do the same thing. 
:s/Copyright \zs2007\ze All Rights Reserved/2008/  2007->2008 \zs \ze 
    start and end
:%s//bar/g 
    you need press "*" to search first
:%s/\<foo\>.*//
    On each line, delete the whole word "foo" and all following text (to end of line). 
:s/^\(\w\)/\u\1/
    If the first character at the beginning of the current line only is lowercase, switch it to uppercase using \u



** 显示换行
如果你使用以下命令进入<list mode>，那么就可以清楚的看到以“$”表示的换行符和以“^I”表示的制表符。
:set list 

* hrd
cd /usr/local/ac/config/; sed -i  '/notify_mac/d'  hr.conf ; sed -i '2i\notify_mac = 0' hr.conf 
* dhcp
** dhcp不能编译,原因是文件里面携带了 \r 
find . -type f |xargs file |grep CR|awk -F : '{print $1}'|xargs sed -i 's!\r!!' 

* vpn
fail:
pptpsetup --create vpn --server 10.1.1.85 --username fangzheng --password www8gbcom9COM~CN! --encrypt --start
OK:
(pppd call vpn logfd 2 nodetach debug dump refuse-eap &)
route add default gw 192.168.168.106 

* yum
yum groupinstall -y   "Desktop"   "Desktop Platform"   "Desktop Platform Development"　 "Fonts" 　"General Purpose Desktop"　 "Graphical Administration Tools"　 "Graphics Creation Tools" 　"Input Methods" 　"X Window System" 　"Chinese Support [zh]"　"Internet Browser" 

* color
  \e[0;32m $PWD \e[0m 
* awk
tail -n 1 /samba/sh000001.org|awk '{ i=1;while(i<NF) {if((i%4)==1) {print $i,$(i+1),$(i+2),$(i+3)} i=i+4}}' 
tail -n 3 /samba/sh000001.org|head -n 1|awk '{ i=1;while(i<NF) {if((i%4)==1) {print $i,$(i+1),$(i+2),$(i+3)} i=i+4}}'
* tail
tail -n 3 /samba/sh000001.org |head -n 1| awk '{ i=1;while(i<NF) {if((i%4)==1) {print $i,$(i+1),$(i+2),$(i+3)} i=i+4}}'  打印倒数第二行
* emacs
修改字体大小，M-x,customize,Faces,Basic Faces,Default,Height->修改pt值
* ssh
内网ssh设置
ssh -NfR 7777:localhost:22 root@180.168.191.198
公网ssh设置：
ssh -NfL 0.0.0.0:5555:localhost:7777 localhost
家里访问：
ssh root@180.168.191.198 -p 5555
更简单的方法(服务器sshd_config配置开启gatewayports)：
ssh -NfR 0.0.0.0:9990:localhost:22 root@180.168.191.198 -o GatewayPorts=yes -o ConnectTimeout=10  -o ConnectionAttempts=5 -o ServerAliveInterval=2

你家里的电脑只要这么访问：
ssh root@180.168.191.198 -p 9990

* qstartdic
* align
:AlignCtrl l 左对齐
:AlignCtrl r 右对齐
:AlignCtrl lrlr 第一部分左对齐，第二部分右对其 ...
:AlignCtrl lp0P0 左对其, 左空一，右空一
